# Generated by Django 4.2.9 on 2024-01-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cart_id',
        ),
    ]
