# Generated by Django 4.2.9 on 2024-01-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_booking_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cart_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
            preserve_default=False,
        ),
    ]
