# Generated by Django 4.2.9 on 2024-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_booking_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='licence',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
