# Generated by Django 4.2.9 on 2024-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_booking_prescription_pharmacy_licence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prescription_required',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
