# Generated by Django 4.2.9 on 2024-03-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_prescription_remove_booking_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='prescription_id',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
