# Generated by Django 4.2.9 on 2024-03-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_prescription_booking_prescription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product'),
        ),
    ]
