# Generated by Django 4.2.9 on 2024-03-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_prescription_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
            preserve_default=False,
        ),
    ]
